version: "3.3"

services:
  ########################################
  ############### Database ###############
  ########################################
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file: ./env/postgres.dev.env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer:latest
    ports:
      - 8080:8080
    depends_on:
      - postgres
